variables:
  homepage: https://github.com/caarlos0/speedtest-exporter
  repository: https://github.com/caarlos0/speedtest-exporter
  description: Exports Speedtest results to the Prometheus format

includes:
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/build.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/package.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/release.yml
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/docker.yml

before:
  hooks:
    - go mod tidy

nfpms:
- overrides:
    deb:
      dependencies:
        - speedtest
    rpm:
      dependencies:
        - speedtest

brews:
- dependencies:
    - name: speedtest

furies:
- account: caarlos0
